export const skillsData = [
    {
        category: "frontend",
        title: "Frontend",
        icon: "💻",
        stacks: [
            "React.js",
            "Next.js",
            "JavaScript",
            "TypeScript",
            "React Query",
            "Recoil",
            "React Hook Form",
            "Framer Motion",
            "Styled Components",
            "Sass",
            "Tailwind CSS",
            "Ant Design",
            "Bootstrap",
            "HTML5",
            "CSS3",
            "SCSS",
            "jQuery",
        ],
    },
    {
        category: "backend",
        title: "Backend",
        icon: "🗄️",
        stacks: ["Firebase", "Prisma", "Planetscale"],
    },
    {
        category: "version",
        title: "Version Control",
        icon: "📁",
        stacks: ["Git", "GitHub", "Bitbucket", "Jira"],
    },
    {
        category: "tools",
        title: "Design Tools",
        icon: "✏️",
        stacks: ["Figma", "Zeplin", "Adobe Photoshop", "Adobe Illustrator"],
    },
];
